{
	"version": 1647832147,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/ground.png",
		"images/fruit-sheet0.png",
		"images/bg.png",
		"images/kunai-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/enemy-sheet0.png",
		"images/enemy2-sheet0.png",
		"images/laser-sheet0.png",
		"images/endline-sheet0.png",
		"images/sprite-sheet0.png",
		"images/playbt-sheet0.png",
		"images/restartbt-sheet0.png",
		"images/undergroundline.png",
		"images/barrel-sheet0.png",
		"images/box-sheet0.png",
		"media/jump.m4a",
		"media/jump.ogg",
		"media/nff-little-bonus.m4a",
		"media/nff-little-bonus.ogg",
		"media/swipe blade slash clang 03.m4a",
		"media/swipe blade slash clang 03.ogg",
		"media/melodyloops-the-first-light.m4a",
		"media/melodyloops-the-first-light.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"pathfind.js"
	]
}